name: ClickHouse Dev Battlestation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7-dind

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Spin up cluster
        run: docker-compose up -d

      - name: Wait for ClickHouse to be ready
        run: |
          for i in {1..30}; do
            echo "⏳ Waiting for ClickHouse..."
            if docker exec ch-node1 clickhouse-client \
              --user=admin --password=admin_strong_password \
              --query "SELECT 1"; then
              echo "✅ ClickHouse is ready!"
              exit 0
            fi
            sleep 5
          done
          echo "❌ ClickHouse did not become ready in time."
          exit 1

      - name: Confirm all nodes are running
        run: |
          for NODE in ch-node1 ch-node2 ch-node3; do
            echo "🔍 Checking $NODE status..."
            if ! docker inspect -f '{{.State.Running}}' $NODE | grep true; then
              echo "❌ $NODE is not running!"
              docker logs $NODE || true
              exit 1
            fi
          done

      - name: Copy schema SQL into container
        run: docker cp ./init/01_create_tables.sql ch-node1:/tmp/01_create_tables.sql

      - name: Create schema tables
        run: |
          docker exec ch-node1 bash -c "clickhouse-client \
            --user=admin --password=admin_strong_password \
            --multiquery < /tmp/01_create_tables.sql"

      - name: Copy CSVs into each node
        run: |
          for NODE in ch-node1 ch-node2 ch-node3; do
            for FILE in user_activity sales_orders system_logs; do
              docker cp ./data/${FILE}.csv $NODE:/tmp/${FILE}.csv || echo "⚠️ Missing ./data/${FILE}.csv"
            done
          done

      - name: Make dev-load.sh executable
        run: chmod +x ./scripts/dev-load.sh

      - name: Run data load script
        run: ./scripts/dev-load.sh

      - name: Validate data in ch-node1
        run: |
          docker exec ch-node1 clickhouse-client \
            --user=admin --password=admin_strong_password \
            --query "SELECT 'user_activity:', count(*) FROM default.user_activity_local"
          docker exec ch-node1 clickhouse-client \
            --user=admin --password=admin_strong_password \
            --query "SELECT 'sales_orders:', count(*) FROM default.sales_orders_local"
          docker exec ch-node1 clickhouse-client \
            --user=admin --password=admin_strong_password \
            --query "SELECT 'system_logs:', count(*) FROM default.system_logs_local"

      - name: Tear down cluster
        run: docker-compose down -v
